apiVersion: v1
kind: Template
metadata:
  name: actuator-demo-imagestream
  labels:
    app: actuator-demo
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 2
    labels:
      app: actuator-demo
    name: actuator-demo
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.210.183:5000/ninech-actuator/actuator-demo:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.210.183:5000/ninech-actuator/actuator-demo:master
      generation: null
      importPolicy: {}
      name: master
      referencePolicy:
        type: ""
