apiVersion: v1
kind: Template
metadata:
  name: actuator-demo-imagestream
  labels:
    app: actuator-demo
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 2
    labels:
      app: actuator-demo
    name: actuator-demo
  spec:
    lookupPolicy:
      local: false
    tags: []
